# This is a basic workflow to help you get started with Actions

name: OnToology

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Validate dir
        run: |
          cd $GITHUB_WORKSPACE ; ls -ltra
      - name: Download OOPS! report Generator
        run: |
          git clone https://github.com/OnToology/oops-report.git
          cd oops-report; pip install -r requirements.txt; python main.py --outputdir $GITHUB_WORKSPACE --ontologydir $GITHUB_WORKSPACE/alo.owl --verbose true
      - name: Git Push
        run: |
          cd $GITHUB_WORKSPACE
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          rm -Rf oops-report;  git add . ; git commit -m 'OnToology GitHub Action push' ; git push origin main
