# This is a basic workflow to help you get started with Actions

name: OnToology

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download Widoco
        run: |
          cd $GITHUB_WORKSPACE ; wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.14/widoco-1.4.14-jar-with-dependencies.jar
      - name: Download OOPS! report Generator
        run: |
          cd $GITHUB_WORKSPACE ; git clone https://github.com/OnToology/oops-report.git
      - name: Make OnToology directory
        run: |
          cd $GITHUB_WORKSPACE ; mkdir -p OnToology;

      - name: Make alo.owl directory
        run: |
          cd $GITHUB_WORKSPACE/OnToology; mkdir -p alo.owl; cd alo.owl; mkdir -p documentation; mkdir -p evaluation; wget https://raw.githubusercontent.com/ahmad88me/demo/master/OnToology/alo.owl/OnToology.cfg
      - name: Generate Documentation
        run: |
          cd $GITHUB_WORKSPACE ; java -jar -Dfile.encoding=utf-8 widoco.jar -ontFile alo.owl -outFolder OnToology/alo.owl/documentation -getOntologyMetadata -licensius -htaccess -lang en
      - name: Download OOPS! report Generator
        run: |
          cd oops-report; pip install -r requirements.txt; python main.py --outputdir OnToology/evaluation --ontologydir ../alo.owl --verbose true

